apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHt9LAogICJwbHVnaW5zIjogewogICAgIi14LWNsaS1oaW50cyI6IHsKICAgICAgImVuYWJsZWQiOiAidHJ1ZSIKICAgIH0KICB9LAogICJmZWF0dXJlcyI6IHsKICAgICJob29rcyI6ICJ0cnVlIgogIH0KfQo=
type: kubernetes.io/dockerconfigjson
